Add support for GCS as storage driver
falcondev-oss/github-actions-cache-server pull request #60
Opened 2024-09-03 10:05 UTC by kishorviswanathan

2024-09-04 14:08 UTC, LouisHaftmann commented
Looks good but we still need to find a way to add tests for this. Are there any gcs emulators for local development?

2024-09-04 16:38 UTC, kishorviswanathan commented
@LouisHaftmann I found [this](https://github.com/fsouza/fake-gcs-server), will give it a try.

2024-09-04 18:05 UTC, kishorviswanathan commented
@LouisHaftmann I have added the test and that helped me to identify a bug. Thanks for the suggestion.

2024-09-05 05:21 UTC, LouisHaftmann requested changes
Just one tiny nitpick: Could we rename `STORAGE_GCS_SERVICEACCOUNT_KEY` to `STORAGE_GCS_SERVICE_ACCOUNT_KEY` for the sake of consistency?

2024-09-05 05:21 UTC, LouisHaftmann commented on storage-drivers/gcs.ts
> +    STORAGE_GCS_SERVICEACCOUNT_KEY: z.string().optional(),
```suggestion
    STORAGE_GCS_SERVICE_ACCOUNT_KEY: z.string().optional(),
```

2024-09-05 05:21 UTC, LouisHaftmann commented on storage-drivers/gcs.ts
> +      keyFilename: options.STORAGE_GCS_SERVICEACCOUNT_KEY,
```suggestion
      keyFilename: options.STORAGE_GCS_SERVICE_ACCOUNT_KEY,
```

2024-09-05 05:21 UTC, LouisHaftmann commented on docs/content/2.storage-drivers/gcs.md
> +#### `STORAGE_GCS_SERVICEACCOUNT_KEY`
```suggestion
#### `STORAGE_GCS_SERVICE_ACCOUNT_KEY`
```

2024-09-05 05:21 UTC, LouisHaftmann commented on docs/content/2.storage-drivers/gcs.md
> +      STORAGE_GCS_SERVICEACCOUNT_KEY: /gcp/config/application_default_credentials.json
```suggestion
      STORAGE_GCS_SERVICE_ACCOUNT_KEY: /gcp/config/application_default_credentials.json
```

2024-09-05 05:33 UTC, kishorviswanathan commented
Done. Renamed it.

2024-09-05 05:46 UTC, LouisHaftmann approved these changes

2024-09-05 05:49 UTC, LouisHaftmann commented
Thank you! :heart:

2024-09-05 05:49 UTC, merged

2024-09-05 05:51 UTC, LouisHaftmann commented
Will be available in the next release. You can check it out now with the dev image `ghcr.io/falcondev-oss/github-actions-cache-server:dev`